/**
 * Definições centrais do jogo.
 */

export const APP_INFO = {
  subtitle: 'Treine sua lógica e complete o quadrado mágico!',
  tagline: 'Puzzle matemático educativo',
  version: '1.0.0',
  year: '2026',
};

export const CREDITS = {
  teamIntro:
    'O Quadrado Mágico é um projecto educativo desenvolvido em Angola, resultante da parceria entre a visão pedagógica original e a implementação digital. Conheça quem concebeu, desenvolveu e deu forma a esta experiência de aprendizagem.',
  developer: {
    role: 'Desenvolvimento',
    title: 'Programador · Designer de Interface · Áudio',
    name: 'Geraldo de Assunção Simba Sense',
    shortName: 'Geraldo Sense',
    description:
      'Responsável pela concepção técnica, programação e experiência completa do jogo — desde a arquitectura dos 150 níveis até ao design visual, sons e jogabilidade em dispositivos móveis.',
    contributions: [
      'Desenvolvimento integral da aplicação web',
      'Sistema de níveis, estatísticas e conquistas',
      'Interface, música, efeitos sonoros e optimização mobile',
    ],
    photos: [
      {
        src: 'assets/team/geraldo-sense-2.png',
        alt: 'Geraldo Sense — retrato profissional',
        variant: 'main',
      },
      {
        src: 'assets/team/geraldo-sense-1.png',
        alt: 'Geraldo Sense — desenvolvedor do projecto',
        variant: 'secondary',
      },
    ],
  },
  ideaProvider: {
    role: 'Concepção',
    title: 'Autor da Ideia Original · Orientação Pedagógica',
    name: 'José Banganga Brás António',
    shortName: 'José Banganga',
    description:
      'Autor original do conceito deste quebra-cabeça matemático e da abordagem pedagógica que o sustenta. A sua ideia de usar o quadrado mágico como ferramenta de raciocínio lógico deu origem a todo o projecto.',
    contributions: [
      'Ideia original do puzzle três vezes três',
      'Fundamentação pedagógica e objectivos de aprendizagem',
      'Inspiração para a evolução do jogo educativo',
    ],
    photos: [
      {
        src: 'assets/team/jose-banganga.png',
        alt: 'José Banganga Brás António — autor da ideia original',
        variant: 'main',
      },
    ],
  },
  aboutSections: [
    {
      title: 'Sobre o Projecto',
      content:
        'O Quadrado Mágico é uma aplicação educativa gratuita que desafia o jogador a completar grelhas numéricas em três dimensões — 3×3, 4×4 e 5×5 — totalizando 150 níveis progressivos. Cada puzzle exige lógica, cálculo mental e estratégia, sem repetir números e respeitando a soma mágica de cada linha, coluna e diagonal.',
    },
    {
      title: 'Objectivo Pedagógico',
      items: [
        'Desenvolver o raciocínio lógico e o pensamento matemático',
        'Reforçar o cálculo mental de forma lúdica e progressiva',
        'Estimular a resolução de problemas com autonomia e persistência',
        'Promover o aprendizagem através de desafios graduados e recompensas',
      ],
    },
    {
      title: 'Origem do Jogo',
      content:
        'Este projecto nasceu da ideia de transformar um exercício clássico de matemática — o quadrado mágico — num jogo digital acessível, envolvente e adaptado ao contexto educativo angolano. A visão pedagógica de José Banganga Brás António foi materializada por Geraldo Sense numa experiência interactiva completa, com níveis, estatísticas, conquistas e interface optimizada para telemóvel.',
    },
  ],
};

export const GAME_DEFINITION = {
  id: 'quadrado-magico-3x3',
  title: 'QUADRADO MÁGICO',
  subtitle: 'Puzzle matemático 3×3',
  grid: { rows: 3, cols: 3, size: 9 },
  numbers: {
    min: 1,
    max: 9,
    pool: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  targetSum: 15,
  winConditions: [
    { id: 'rows', label: '3 linhas', type: 'rows' },
    { id: 'cols', label: '3 colunas', type: 'cols' },
    { id: 'diag-main', label: 'Diagonal principal', type: 'diagonal', index: 0 },
    { id: 'diag-sec', label: 'Diagonal secundária', type: 'diagonal', index: 1 },
  ],
};

export const GAME_RULES = {
  summary:
    'Preencha o quadro 3×3 utilizando os números de 1 a 9 (sem repetir nenhum número), de modo que a soma de todos os números em cada linha, em cada coluna e nas duas diagonais seja sempre 15.',
  howToPlay: [
    'Selecione um número na barra inferior ou arraste-o para um quadrado vazio.',
    'Use cada número apenas uma vez.',
    'Tem no máximo 3 erros por jogo — ao terceiro erro, perde.',
    'Cada nível permite no máximo 1 dica; níveis difíceis não têm dicas.',
    'Complete quando todas as linhas, colunas e diagonais somarem o alvo.',
  ],
  tips: [
    'Use cada número apenas uma vez.',
    'Comece pelas linhas ou colunas que já têm números.',
    'O número 5 fica sempre no centro num quadrado mágico 3×3!',
  ],
};

export const UI_LABELS = {
  loading: 'Carregando...',
  menu: {
    play: 'JOGAR',
    selectLevel: 'SELECIONAR NÍVEL',
    stats: 'ESTATÍSTICAS',
    howToPlay: 'COMO JOGAR',
    info: 'INFORMAÇÃO',
    comingSoon: 'Funcionalidade em breve!',
    allComplete: 'Parabéns! Completou todos os 150 níveis!',
    rewards: 'RECOMPENSAS',
    daily: 'DIÁRIO',
    achievements: 'CONQUISTAS',
    shop: 'LOJA',
  },
  nav: {
    home: 'Início',
    levels: 'Níveis',
    stats: 'Estatísticas',
    settings: 'Configurações',
  },
  levels: {
    title: 'Selecionar Nível',
    complete: 'Completo',
    play: 'JOGAR',
    locked: 'Bloqueado',
    clues: 'pistas',
    worldDesc: 'Níveis {from}–{to} · Quadrado {grid}',
  },
  stats: {
    title: 'ESTATÍSTICAS',
    scoreLabel: 'Pontuação total',
    totalStars: 'Estrelas ganhas',
    levelsCompleted: 'Níveis completos',
    totalTime: 'Tempo de jogo',
    perfectLevels: 'Níveis perfeitos (3★)',
    totalHints: 'Dicas usadas',
    totalErrors: 'Erros cometidos',
    noHintWins: 'Vitórias sem dicas',
    achievements: 'Conquistas',
    viewAchievements: 'VER CONQUISTAS',
    unlocked: 'desbloqueados',
  },
  achievements: {
    title: 'CONQUISTAS',
    unlocked: 'Desbloqueada',
  },
  settings: {
    title: 'DEFINIÇÕES',
    subtitle: 'Personalize a sua experiência e gerencie as suas preferências.',
    general: 'GERAL',
    game: 'JOGO',
    about: 'SOBRE',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeAuto: 'Automático',
    accentColor: 'Cor de Destaque',
    numberStyle: 'Estilo dos Números',
    numberStandard: 'Padrão',
    numberModern: 'Moderno',
    animations: 'Animações',
    masterVolume: 'Volume Geral',
    sound: 'Efeitos Sonoros',
    music: 'Música de Fundo',
    vibration: 'Vibração',
    soundVolume: 'Volume dos efeitos',
    musicVolume: 'Volume da música',
    previewSound: 'Reproduzir Sons',
    showErrors: 'Verificar Erros',
    confirmRestart: 'Confirmação ao Reiniciar',
    confirmMoves: 'Confirmar Movimentos',
    hintsEnabled: 'Permitir Dicas',
    timerEnabled: 'Cronómetro',
    defaultDifficulty: 'Dificuldade Padrão',
    inputMode: 'Modo de Entrada',
    inputTap: 'Toque',
    inputDrag: 'Arrastar',
    inputBoth: 'Ambos',
    howToPlay: 'Regras do Jogo',
    notificationsEnabled: 'Permitir Notificações',
    reminders: 'Lembretes',
    dailyReminder: 'Lembrete Diário',
    dailyChallenge: 'Desafio Diário',
    progressNotifsTitle: 'Progresso',
    achievementNotifs: 'Conquistas',
    progressNotifs: 'Melhorias',
    otherNotifs: 'Outros',
    newsNotifs: 'Novidades',
    promoNotifs: 'Promoções',
    privacyPolicy: 'Política de Privacidade',
    termsOfUse: 'Termos de Uso',
    shareData: 'Partilhar Dados Anónimos',
    clearLocalData: 'Apagar Dados Locais',
    clearLocalDataNote: 'Remove progresso, estatísticas e conquistas deste dispositivo.',
    aboutGame: 'Informação e Créditos',
    viewStats: 'Ver Estatísticas',
    restoreDefaults: 'Restaurar Definições',
    confirmReset: 'Restaurar todas as definições para os valores padrão?',
    confirmClearData: 'Apagar todo o progresso e definições? Esta ação não pode ser desfeita.',
    resetDone: 'Definições restauradas.',
    clearDone: 'Dados locais apagados.',
    close: 'Guardar',
    sections: {
      appearance: { title: 'Aparência', subtitle: 'Temas, cores e interface' },
      sound: { title: 'Som e Música', subtitle: 'Definições de áudio' },
      gameplay: { title: 'Jogabilidade', subtitle: 'Dificuldade e regras do jogo' },
      notifications: { title: 'Notificações', subtitle: 'Alertas e lembretes' },
      privacy: { title: 'Privacidade e Segurança', subtitle: 'Dados e permissões' },
      about: { title: 'Sobre o Jogo', subtitle: 'Informação e versão' },
    },
    privacyText: 'O Quadrado Mágico guarda apenas dados locais no seu dispositivo (progresso, estatísticas e preferências). Não recolhemos informação pessoal nem enviamos dados para servidores externos.',
    termsText: 'Ao utilizar este jogo educativo, concorda em usá-lo para fins de aprendizagem. O conteúdo é propriedade dos respetivos autores. O jogo é fornecido "como está", sem garantias.',
  },
  info: {
    title: 'INFORMAÇÃO',
    credits: 'A Nossa Equipa',
    teamSubtitle: 'Quem está por trás do projecto',
    contributions: 'Contribuições',
    back: '←',
  },
  howToPlay: {
    title: 'COMO JOGAR',
    rules: 'Regras',
    example: 'EXEMPLO',
    tips: 'DICAS',
    start: 'VAMOS JOGAR!',
    back: '←',
  },
  objective: {
    title: 'OBJETIVO',
    description:
      'A soma de todos os números em cada linha, coluna e diagonal deve ser igual a:',
  },
  progress: { title: 'PROGRESSO' },
  pool: {
    hint: 'Máximo 3 erros por jogo. Use cada número apenas uma vez.',
  },
  game: {
    back: '←',
    pause: 'Pausar',
    resume: 'Continuar',
    undo: 'Desfazer',
    erase: 'Apagar',
    restart: 'Reiniciar',
    hint: 'Dica',
    victory: 'PARABÉNS! Quadrado mágico concluído!',
    victoryShort: 'PARABÉNS!',
    nextLevel: 'PRÓXIMO NÍVEL',
    tryAgain: 'JOGAR NOVAMENTE',
    gameOver: 'Fim de Jogo!',
    gameOverSubtitle: 'Não foi desta vez. Mas você chegou lá!',
    gameOverMsg: 'O quadrado está incorreto. Verifique as somas das linhas, colunas e diagonais.',
    gameOverErrors: 'Esgotou as 3 tentativas! Tente novamente com mais cuidado.',
    gameOverAttempts: 'TENTATIVAS',
    gameOverBestTime: 'MELHOR TEMPO',
    gameOverMotivation: 'A prática leva à perfeição! Continue treinando e supere seu melhor tempo.',
    gameOverRestartSub: 'Tentar novamente este nível',
    gameOverLevelsSub: 'Escolher outro nível',
    gameOverExitSub: 'Voltar ao menu inicial',
    gameOverSelectLevel: 'Selecionar Nível',
    gameOverExit: 'Sair do Jogo',
    errorsRemaining: 'Erros restantes',
    noHints: 'Sem dicas neste nível',
    blankLevel: 'Do zero',
    restartMatch: 'Reiniciar Encontro',
    confirmRestart: 'Tem certeza que deseja reiniciar este nível?',
    confirmYes: 'Sim, Reiniciar',
    confirmCancel: 'Cancelar',
    pauseTitle: 'Pausa',
    pauseContinue: 'Continuar',
    pauseRestart: 'Reiniciar',
    pauseUndo: 'Desfazer',
    pauseLevels: 'Selecionar Nível',
    pauseStats: 'Estatísticas',
    pauseSettings: 'Configurações',
    pauseExit: 'Sair',
    time: 'Tempo',
    hintsUsed: 'Dicas usadas',
    errors: 'Erros',
  },
};
