/**
 * Definições centrais do jogo.
 */

export const APP_INFO = {
  subtitle: 'Treine a sua lógica e complete o quadrado mágico!',
  tagline: 'Puzzle matemático educativo',
  version: '2.0.0',
  year: '2026',
};

export const CREATOR_FLOAT = {
  photo: 'assets/team/geraldo-sense-2.png',
  name: 'Geraldo Sense',
  fullName: 'Geraldo de Assunção Simba Sense',
  label: 'Criador do Jogo',
  photoPosition: '50% 8%',
};

export const CREDITS = {
  teamIntro:
    'O Quadrado Mágico é uma aplicação educativa angolana, criada por Geraldo de Assunção Simba Sense. O projecto nasceu após a resolução de um desafio matemático partilhado no WhatsApp — conheça abaixo o criador do jogo e o contexto que deu origem a esta experiência.',
  developer: {
    role: 'Criador do Jogo',
    title: 'Autor do Projecto · Programação · Design de Interface',
    name: 'Geraldo de Assunção Simba Sense',
    shortName: 'Geraldo Sense',
    description:
      'Autor conceptual, criador e desenvolvedor integral desta aplicação. Quando José Banganga publicou no WhatsApp um desafio de quadrado mágico 3×3, Geraldo demonstrou ser capaz de o resolver correctamente. Por iniciativa própria, teve então a ideia de transformar esse exercício num jogo digital educativo — conceptualizando e materializando uma aplicação completa com 150 níveis, estatísticas, conquistas e interface optimizada para telemóvel.',
    contributions: [
      'Ideia autónoma de transformar o desafio num jogo digital',
      'Autoria conceptual e criação integral da aplicação',
      'Arquitectura dos 150 níveis, estatísticas e conquistas',
      'Design de interface, banda sonora, efeitos sonoros e optimização mobile',
    ],
    photos: [
      {
        src: 'assets/team/geraldo-sense-2.png',
        alt: 'Geraldo Sense — criador do Quadrado Mágico',
        variant: 'main',
        position: '50% 10%',
        fit: 'cover',
      },
      {
        src: 'assets/team/geraldo-sense-1.png',
        alt: 'Geraldo Sense — autor e desenvolvedor',
        variant: 'secondary',
        position: '50% 12%',
        fit: 'cover',
      },
    ],
  },
  ideaProvider: {
    role: 'Desafio Original',
    title: 'Autor da Publicação no WhatsApp',
    name: 'José Banganga Brás António',
    shortName: 'José Banganga',
    description:
      'Publicou no WhatsApp um desafio matemático baseado no quadrado mágico 3×3. A partilha despertou curiosidade e permitiu que Geraldo Sense demonstrasse a resolução correcta da grelha — momento que precedeu, por iniciativa de Geraldo, a concepção deste jogo educativo.',
    contributions: [
      'Publicação do desafio original no WhatsApp',
      'Partilha informal do puzzle que despertou o interesse',
      'Estímulo inicial que antecedeu a ideia do jogo',
    ],
    photos: [
      {
        src: 'assets/team/jose-banganga.png',
        alt: 'José Banganga Brás António — autor do desafio WhatsApp',
        variant: 'main',
        position: '50% 15%',
        fit: 'cover',
      },
    ],
  },
  aboutSections: [
    {
      title: 'Sobre o Projecto',
      content:
        'O Quadrado Mágico é uma aplicação educativa gratuita que desafia o jogador a completar grelhas numéricas em três dimensões — 3×3, 4×4 e 5×5 — totalizando 150 níveis progressivos. Cada puzzle exige lógica, cálculo mental e estratégia, sem repetir números e respeitando a soma mágica de cada linha, coluna e diagonal.',
    },
    {
      title: 'Objectivo Pedagógico',
      items: [
        'Desenvolver o raciocínio lógico e o pensamento matemático',
        'Reforçar o cálculo mental de forma lúdica e progressiva',
        'Estimular a resolução de problemas com autonomia e persistência',
        'Promover a aprendizagem através de desafios graduados e recompensas',
      ],
    },
    {
      title: 'Origem do Jogo',
      content:
        'Tudo começou quando José Banganga Brás António publicou no WhatsApp um desafio: completar um quadrado mágico 3×3. Geraldo de Assunção Simba Sense demonstrou que conseguia resolver a grelha correctamente. A partir desse momento — por iniciativa própria — Geraldo teve a ideia de transformar o exercício num jogo digital educativo e desenvolveu integralmente esta aplicação, com múltiplos mundos, estatísticas e conquistas. O mérito de José Banganga reside na partilha do desafio que serviu de estímulo; a ideia, concepção e realização do jogo são inteiramente de Geraldo Sense.',
    },
  ],
};

export const GAME_DEFINITION = {
  id: 'quadrado-magico-3x3',
  title: 'QUADRADO MÁGICO',
  subtitle: 'Puzzle matemático 3×3',
  grid: { rows: 3, cols: 3, size: 9 },
  numbers: {
    min: 1,
    max: 9,
    pool: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  targetSum: 15,
  winConditions: [
    { id: 'rows', label: '3 linhas', type: 'rows' },
    { id: 'cols', label: '3 colunas', type: 'cols' },
    { id: 'diag-main', label: 'Diagonal principal', type: 'diagonal', index: 0 },
    { id: 'diag-sec', label: 'Diagonal secundária', type: 'diagonal', index: 1 },
  ],
};

export const GAME_RULES = {
  summary:
    'Preencha o quadro 3×3 utilizando os números de 1 a 9 (sem repetir nenhum número), de modo que a soma de todos os números em cada linha, em cada coluna e nas duas diagonais seja sempre 15.',
  howToPlay: [
    'Selecione um número na barra inferior ou arraste-o para um quadrado vazio.',
    'Use cada número apenas uma vez.',
    'Tem no máximo 3 erros por jogo — ao terceiro erro, perde.',
    'Cada nível permite no máximo 1 dica; níveis difíceis não têm dicas.',
    'Complete quando todas as linhas, colunas e diagonais somarem o alvo.',
  ],
  tips: [
    'Use cada número apenas uma vez.',
    'Comece pelas linhas ou colunas que já têm números.',
    'O número 5 fica sempre no centro num quadrado mágico 3×3!',
  ],
};

export const UI_LABELS = {
  loading: 'Carregando...',
  menu: {
    play: 'JOGAR',
    selectLevel: 'SELECIONAR NÍVEL',
    stats: 'ESTATÍSTICAS',
    howToPlay: 'COMO JOGAR',
    info: 'INFORMAÇÃO',
    comingSoon: 'Funcionalidade em breve!',
    allComplete: 'Parabéns! Completou todos os 150 níveis!',
    rewards: 'RECOMPENSAS',
    daily: 'DIÁRIO',
    achievements: 'CONQUISTAS',
    shop: 'LOJA',
  },
  nav: {
    home: 'Início',
    levels: 'Níveis',
    stats: 'Estatísticas',
    settings: 'Configurações',
  },
  levels: {
    title: 'Selecionar Nível',
    complete: 'Completo',
    play: 'JOGAR',
    locked: 'Bloqueado',
    clues: 'pistas',
    worldDesc: 'Níveis {from}–{to} · Quadrado {grid}',
  },
  stats: {
    title: 'ESTATÍSTICAS',
    scoreLabel: 'Pontuação total',
    totalStars: 'Estrelas ganhas',
    levelsCompleted: 'Níveis completos',
    totalTime: 'Tempo de jogo',
    perfectLevels: 'Níveis perfeitos (3★)',
    totalHints: 'Dicas usadas',
    totalErrors: 'Erros cometidos',
    noHintWins: 'Vitórias sem dicas',
    achievements: 'Conquistas',
    viewAchievements: 'VER CONQUISTAS',
    unlocked: 'desbloqueados',
  },
  achievements: {
    title: 'CONQUISTAS',
    unlocked: 'Desbloqueada',
  },
  settings: {
    title: 'DEFINIÇÕES',
    subtitle: 'Personalize a sua experiência e gerencie as suas preferências.',
    general: 'GERAL',
    game: 'JOGO',
    about: 'SOBRE',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeAuto: 'Automático',
    accentColor: 'Cor de Destaque',
    numberStyle: 'Estilo dos Números',
    numberStandard: 'Padrão',
    numberModern: 'Moderno',
    animations: 'Animações',
    masterVolume: 'Volume Geral',
    sound: 'Efeitos Sonoros',
    music: 'Música de Fundo',
    vibration: 'Vibração',
    soundVolume: 'Volume dos efeitos',
    musicVolume: 'Volume da música',
    previewSound: 'Reproduzir Sons',
    showErrors: 'Verificar Erros',
    confirmRestart: 'Confirmação ao Reiniciar',
    confirmMoves: 'Confirmar Movimentos',
    hintsEnabled: 'Permitir Dicas',
    timerEnabled: 'Cronómetro',
    defaultDifficulty: 'Dificuldade Padrão',
    inputMode: 'Modo de Entrada',
    inputTap: 'Toque',
    inputDrag: 'Arrastar',
    inputBoth: 'Ambos',
    howToPlay: 'Regras do Jogo',
    notificationsEnabled: 'Permitir Notificações',
    reminders: 'Lembretes',
    dailyReminder: 'Lembrete Diário',
    dailyChallenge: 'Desafio Diário',
    progressNotifsTitle: 'Progresso',
    achievementNotifs: 'Conquistas',
    progressNotifs: 'Melhorias',
    otherNotifs: 'Outros',
    newsNotifs: 'Novidades',
    promoNotifs: 'Promoções',
    privacyPolicy: 'Política de Privacidade',
    termsOfUse: 'Termos de Uso',
    shareData: 'Partilhar Dados Anónimos',
    clearLocalData: 'Apagar Dados Locais',
    clearLocalDataNote: 'Remove progresso, estatísticas e conquistas deste dispositivo.',
    aboutGame: 'Informação e Créditos',
    viewStats: 'Ver Estatísticas',
    restoreDefaults: 'Restaurar Definições',
    confirmReset: 'Restaurar todas as definições para os valores padrão?',
    confirmClearData: 'Apagar todo o progresso e definições? Esta ação não pode ser desfeita.',
    resetDone: 'Definições restauradas.',
    clearDone: 'Dados locais apagados.',
    close: 'Guardar',
    sections: {
      appearance: { title: 'Aparência', subtitle: 'Temas, cores e interface' },
      sound: { title: 'Som e Música', subtitle: 'Definições de áudio' },
      gameplay: { title: 'Jogabilidade', subtitle: 'Dificuldade e regras do jogo' },
      notifications: { title: 'Notificações', subtitle: 'Alertas e lembretes' },
      privacy: { title: 'Privacidade e Segurança', subtitle: 'Dados e permissões' },
      about: { title: 'Sobre o Jogo', subtitle: 'Informação e versão' },
      reviews: { title: 'Comunidade', subtitle: 'Críticas e mensagens dos jogadores' },
    },
    reviews: {
      communityTitle: 'Comunidade Quadrado Mágico',
      communityIntro: 'Espaço exclusivo dos jogadores — partilhe a sua opinião como numa conversa.',
      communityOnline: 'Comunidade activa',
      communityOffline: 'Modo offline',
      formTitle: 'Enviar mensagem',
      formIntro: 'Escreva a sua crítica e todos os jogadores do jogo verão na comunidade.',
      nameLabel: 'O seu nome',
      namePlaceholder: 'O seu nome…',
      nameHint: 'Aparece na mensagem enviada.',
      ratingLabel: 'Avaliação',
      commentLabel: 'Mensagem',
      commentPlaceholder: 'Escreva a sua crítica sobre o jogo…',
      commentHint: 'Mínimo 10 caracteres.',
      improvementsField: 'Sugestões',
      improvementsToggle: '+ Sugestões de melhoria',
      improvementsPlaceholder: 'Ideias para melhorar o jogo (opcional)…',
      improvementsHint: 'Opcional.',
      improvementsLabel: 'Sugestões',
      submit: 'Enviar',
      submitting: 'A enviar…',
      saved: 'Mensagem enviada para a comunidade!',
      savedOffline: 'Mensagem guardada neste telemóvel. Verifique a ligação à internet.',
      listTitle: 'Mensagens da comunidade',
      listIntro: 'Críticas permanentes de todos os jogadores.',
      totalReviews: 'mensagens',
      emptyList: 'Ainda não há mensagens. Seja o primeiro a falar com a comunidade!',
      refresh: 'Actualizar',
      syncing: 'A sincronizar mensagens…',
      syncError: 'Não foi possível ligar à comunidade. Verifique a internet e toque ↻.',
      syncHint: 'Para sincronizar entre telemóvel e Mac: configure o JSONBin em reviewsConfig.js (instruções no ficheiro) e actualize ambos os dispositivos para v2.0.0.',
      syncActiveNote: 'Comunidade activa — todas as críticas são visíveis para todos os jogadores.',
      localSyncNote: 'Sem ligação à comunidade. As mensagens ficam apenas neste dispositivo.',
      errorName: 'Introduza um nome válido (2 a 48 caracteres).',
      errorRating: 'Seleccione uma avaliação de 1 a 5 estrelas.',
      errorComment: 'A mensagem deve ter pelo menos 10 caracteres.',
      errorImprovements: 'As sugestões excedem o limite de caracteres.',
    },
    privacyText: 'O Quadrado Mágico guarda apenas dados locais no seu dispositivo (progresso, estatísticas e preferências). Não recolhemos informação pessoal nem enviamos dados para servidores externos.',
    termsText: 'Ao utilizar este jogo educativo, concorda em usá-lo para fins de aprendizagem. O conteúdo é propriedade dos respetivos autores. O jogo é fornecido "como está", sem garantias.',
  },
  info: {
    title: 'INFORMAÇÃO',
    credits: 'A Nossa Equipa',
    teamSubtitle: 'Criador e origem do projecto',
    contributions: 'Contribuições',
    back: '←',
  },
  howToPlay: {
    title: 'COMO JOGAR',
    rules: 'Regras',
    example: 'EXEMPLO',
    tips: 'DICAS',
    start: 'VAMOS JOGAR!',
    back: '←',
  },
  objective: {
    title: 'OBJETIVO',
    description:
      'A soma de todos os números em cada linha, coluna e diagonal deve ser igual a:',
  },
  progress: { title: 'PROGRESSO' },
  pool: {
    hint: 'Máximo 3 erros por jogo. Use cada número apenas uma vez.',
  },
  game: {
    back: '←',
    pause: 'Pausar',
    resume: 'Continuar',
    undo: 'Desfazer',
    erase: 'Apagar',
    restart: 'Reiniciar',
    hint: 'Dica',
    victory: 'PARABÉNS! Quadrado mágico concluído!',
    victoryShort: 'PARABÉNS!',
    nextLevel: 'PRÓXIMO NÍVEL',
    tryAgain: 'JOGAR NOVAMENTE',
    gameOver: 'Fim de Jogo!',
    gameOverSubtitle: 'Não foi desta vez. Mas você chegou lá!',
    gameOverMsg: 'O quadrado está incorreto. Verifique as somas das linhas, colunas e diagonais.',
    gameOverErrors: 'Esgotou as 3 tentativas! Tente novamente com mais cuidado.',
    gameOverAttempts: 'TENTATIVAS',
    gameOverBestTime: 'MELHOR TEMPO',
    gameOverMotivation: 'A prática leva à perfeição! Continue treinando e supere seu melhor tempo.',
    gameOverRestartSub: 'Tentar novamente este nível',
    gameOverLevelsSub: 'Escolher outro nível',
    gameOverExitSub: 'Voltar ao menu inicial',
    gameOverSelectLevel: 'Selecionar Nível',
    gameOverExit: 'Sair do Jogo',
    errorsRemaining: 'Erros restantes',
    noHints: 'Sem dicas neste nível',
    blankLevel: 'Do zero',
    restartMatch: 'Reiniciar Encontro',
    confirmRestart: 'Tem certeza que deseja reiniciar este nível?',
    confirmYes: 'Sim, Reiniciar',
    confirmCancel: 'Cancelar',
    pauseTitle: 'Pausa',
    pauseContinue: 'Continuar',
    pauseRestart: 'Reiniciar',
    pauseUndo: 'Desfazer',
    pauseLevels: 'Selecionar Nível',
    pauseStats: 'Estatísticas',
    pauseSettings: 'Configurações',
    pauseExit: 'Sair',
    time: 'Tempo',
    hintsUsed: 'Dicas usadas',
    errors: 'Erros',
  },
};
